### ISSUE TITLE
Deprecated Twig calls

### ISSUE THREAD

**Issue by bennoz** [aptoma/twig-markdown#10]
When using the markdown filter, I am presented with the following warnings:

    DEPRECATED - The Twig_Filter_Method class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.

    DEPRECATED - The Twig_Filter class is deprecated since version 1.12 and will be removed in 2.0. Use Twig_SimpleFilter instead.

    DEPRECATED - Using an instance of "Twig_Filter_Method" for filter "markdown" is deprecated. Use Twig_SimpleFilter instead.

**Comment by gunnarlium** [comment]
Fixed in a06e723.
