### ISSUE TITLE
Twig 2.x support

### ISSUE THREAD

**Issue by DavidGarciaCat** [aptoma/twig-markdown#25]
Hello,

Can you please confirm if this library is working with Twig 2.x please?

Thanks,

**Comment by gunnarlium** [comment]
Hi,

I have not tested this with Twig 2, but there'a an ongoing pull request to support it: https://github.com/aptoma/twig-markdown/pull/24 Feel free to help that PR pass the Travis build, to be ready for merging.

**Comment by c9s** [comment]
Same here

**Comment by gunnarlium** [comment]
I'll look into moving to Twig 2.

**Comment by gunnarlium** [comment]
Fixed in v3.0.0.

I've dropped support for Twig 1, but v2 can of course still be used.

**Comment by c9s** [comment]
Thanks!

**Comment by DavidGarciaCat** [comment]
Thank you!
