### ISSUE TITLE
How to get in touch regarding a security concern

### ISSUE THREAD

**Issue by psmoros** [aptoma/twig-markdown#44]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@rudloff) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by gunnarlium** [comment]
Hi,

Thanks for reaching out. We are no longer maintaining this package, and will not make any new releases. If you want, you can fork the repo and create a new package, with your fix applied.

**Comment by Rudloff** [comment]
Thanks for the explanation.
I suggest marking the package as abandoned on https://packagist.org/packages/aptoma/twig-markdown so that people can be warned by Composer when installing it.

**Comment by gunnarlium** [comment]
Done.
